# -*- coding: utf-8 -*-
"""Maksa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mlHyeTGsfI9HdsMVD31Ttdnn7iknuzVk
"""

while True:
    masukan = input('Apakah kamu cinta padaku ? ')
    if masukan.lower() in ('ya','iya','y','pasti','tentu','tentu saja','yup','yes'):
        break
print('I Love You Too!')